name: ukulimabora
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lint: ^1.5.3
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  firebase_analytics: ^8.1.2
  cloud_firestore: ^2.2.2
  country_code_picker: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
 
