name: ukulimabora
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lint: ^1.5.3
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  firebase_analytics: ^8.1.2
  cloud_firestore: ^2.2.2
  country_code_picker: ^2.0.2
  google_maps_flutter: ^2.0.8
  percent_indicator: ^3.0.1
  flutter_google_places: ^0.3.0
  provider: ^6.0.1
  geolocator: ^7.6.2
  http: ^0.13.3
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
 
